#!/bin/bash

_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $UPSTREAM_REPO == "Redthon-Ar" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL3RlbGV0aG9uQXIvVGVsZXRob25BcmFiL2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    elif [[ $UPSTREAM_REPO == "Redthon-Ar" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL3RlbGV0aG9uQXIvVGVsZXRob25BcmFiL2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    elif [[ $UPSTREAM_REPO =~ $regex ]]
    then
        if [[ $UPSTREAM_REPO_BRANCH ]]
        then
            echo "${UPSTREAM_REPO}/archive/${UPSTREAM_REPO_BRANCH}.zip"
        else
            echo "${UPSTREAM_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL3RlbGV0aG9uQXIvVGVsZXRob25BcmFiL2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    fi
}


_setting_bot () {
    local zippath
    zippath="RedthonBot.zip"
    echo "   تنـزيــل آكــوآد آلســورس ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  تنـزيــل تخـزيـن آلســورس ..."
    Redthon=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "✓"
    echo "تم الانتهاء"
    rm -rf "$zippath"
    sleep 5
    cd $Redthon
    echo "جـــآر آلآسـتــرآد ردثــون آلـعــرب  ..."
    echo "2
    "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m userbot
}

_setting_bot
